export const mockData = [
  {
    id: 1,
    organisation: 'Witting ',
    username: 'iva_mill',
    email: 'everardo',
    phone: '1-228-367-1',
    start_date: '2023-11-17T00:58:21.213Z',
    status: 'blacklisted',
    fullname: 'Laurence.Olson98',
    bvn: '92038587',
    gender: 'unknown',
    marital_status: 'divorced',
    children: 2,
    type_of_residence: "Parent's apartment",
    level_of_education: "Master's Degree",
    employment_status: 'Unemployed',
    duration_of_employment: '2 years',
    monthly_income: '159.37',
    loan_repayment: '758.10',
    twitter: 'mable75',
    facebook: 'Cedrick.',
    instagram: 'Phyllis_',
    gurarantors_fullname: 'Treva_Kr',
    gurarantors_phone_number: '546.669.',
    gurarantors_email_address: 'mazie_pu',
    gurarantors_relationship: 'brother',
    avatar:
      'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1095.jpg',
    withLoan: true,
    withSavings: true,
    tier: 2,
    account_number: '28905234',
    bank_name: 'Ecobank Nigeria',
  },
  {
    id: 2,
    organisation: 'Schroeder and Sons',
    username: 'mossie',
    email: 'leonora',
    phone: '1-855-689-4',
    start_date: '2023-09-22T08:14:47.623Z',
    status: 'active',
    fullname: 'Alda.Heller75',
    bvn: '73820514',
    gender: 'female',
    marital_status: 'single',
    children: 0,
    type_of_residence: 'Rented apartment',
    level_of_education: "Bachelor's Degree",
    employment_status: 'Employed',
    duration_of_employment: '3 years',
    monthly_income: '2750.65',
    loan_repayment: '1500.25',
    twitter: 'marc',
    facebook: 'Destiney45',
    instagram: 'Marielle7',
    gurarantors_fullname: 'Chanelle_Fe',
    gurarantors_phone_number: '888.555.',
    gurarantors_email_address: 'rosalind',
    gurarantors_relationship: 'friend',
    avatar:
      'https://cloudflare-ipfs.com/ipfs/QmaJDjjfnJkF96eiEeN8UWk2pXUxpxgzxJBVt1sN6f6KVA/avatar/2098.jpg',
    withLoan: false,
    withSavings: true,
    tier: 1,
    account_number: '76543210',
    bank_name: 'GTBank',
  },
  {
    id: 3,
    organisation: 'Lowe and Sons',
    username: 'lottie',
    email: 'kaelyn',
    phone: '1-463-867-8',
    start_date: '2023-08-10T16:32:05.113Z',
    status: 'inactive',
    fullname: 'Alivia17',
    bvn: '43918654',
    gender: 'male',
    marital_status: 'married',
    children: 3,
    type_of_residence: 'Own house',
    level_of_education: 'High School Diploma',
    employment_status: 'Self-employed',
    duration_of_employment: '5 years',
    monthly_income: '4200.00',
    loan_repayment: '2000.75',
    twitter: 'thea',
    facebook: 'Emmet',
    instagram: 'Moriah7',
    gurarantors_fullname: 'Meggie_Ko',
    gurarantors_phone_number: '123.456.',
    gurarantors_email_address: 'destinee',
    gurarantors_relationship: 'cousin',
    avatar:
      'https://cloudflare-ipfs.com/ipfs/QmPzNARPr39S99Jk5hMjrHAYaNbbvvD8GbftmY7WdGsFwr/avatar/3056.jpg',
    withLoan: true,
    withSavings: false,
    tier: 3,
    account_number: '98765432',
    bank_name: 'Zenith Bank',
  },
];
